//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompleteLoginAndRegistration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email_ID { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Password { get; set; }
        public bool isEmailVarified { get; set; }
        public string ImageFile { get; set; }
        public string Gender { get; set; }
        public System.Guid ActivationCode { get; set; }
        public string ConfirmPassword { get; internal set; }
    }
}
